services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    restart: always

  odoo:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons
      - ./setup:/setup
    networks:
      - odoo-network
    restart: always
    command: /setup/entrypoint.sh

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo-network:
