[project]
name = "bd-perf-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "argparse>=1.4.0",
    "babel>=2.17.0",
    "faker",
    "flask>=3.1.0",
    "pytz>=2025.2",
    "werkzeug>=3.1.3",
]
